---
- name: Update Ubuntu machines
  hosts: all
  become: yes  

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes
        autoremove: yes  
    
    - name: Install Nginx
      package:
        name: nginx
        state: present     
        











